name: Accessibility Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  axe-audit:
    uses: berkeley-cdss/course-site-actions/.github/workflows/myst-a11y.yml@main
    with:
      base_url: /${{ github.event.repository.name }}
    permissions:
      contents: write
